name: "Stack deploy"
description: "Deploy an application on a Stack server"
author: "fdev"

inputs:
  app:
    description: "Name of the app"
    required: true
  server:
    description: "Stack server"
    default: "stack.fdev.nl"
    required: false
  ssh-key:
    description: "SSH key used to connect"
    required: true

runs:
  using: "composite"
  steps:
    # https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        cat << END > ~/.ssh/stack.key
        ${{ inputs.ssh-key }}
        END
        chmod 600 ~/.ssh/stack.key
        cat >>~/.ssh/config <<END
        Host stack
          HostName ${{ inputs.server }}
          User deploy
          IdentityFile ~/.ssh/stack.key
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          LogLevel ERROR
        END

    - name: Deploy the application
      shell: bash
      run: ssh stack 'deploy ${{ inputs.app }}'
